import type { ElectionData } from "@/types/election";
import { STATE_FILLS_2024, STATE_RESULTS_2024 } from "@/data/2024-results";
import { LIVE_RESULTS_ENABLED } from "@/lib/feature-flags";

export const SEED_DATA: ElectionData = {
  defaultTab: "notable-races",
  showLiveResults: LIVE_RESULTS_ENABLED,
  stateOfNation: {
    presidential: {
      demName: "Kamala Harris",
      repName: "Donald Trump",
      demImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Kamala_Harris_Vice_Presidential_Portrait.jpg/200px-Kamala_Harris_Vice_Presidential_Portrait.jpg",
      repImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Donald_Trump_official_portrait.jpg/200px-Donald_Trump_official_portrait.jpg",
      demEV: 226,
      repEV: 312,
      demPopularVote: 74_749_891,
      repPopularVote: 77_168_458,
      totalPopularVote: 154_600_000,
      stateFills: STATE_FILLS_2024,
      stateResults: STATE_RESULTS_2024,
      lastUpdated: new Date().toISOString(),
    },
    governors: [
      { state: "Texas", stateCode: "TX", status: "upcoming", note: "2026" },
      { state: "Florida", stateCode: "FL", status: "called", winner: "Ron DeSantis", party: "R" },
    ],
    congress: {
      senateDem: 47,
      senateRep: 53,
      senateInd: 0,
      houseDem: 213,
      houseRep: 220,
      lastUpdated: new Date().toISOString(),
    },
  },
  notableRaces: [
    {
      id: "tx-senate-2026-r",
      title: "Texas U.S. Senate Republican Primary",
      date: "2026-03-03",
      type: "primary",
      office: "congress",
      state: "Texas",
      stateCode: "TX",
      significance: "This race is a high-stakes referendum on the direction of the Texas GOP, pitting four-term incumbent John Cornyn against Attorney General Ken Paxton and U.S. Rep. Wesley Hunt. Cornyn represents the state's traditional conservative establishment, while Paxton has leveraged his \"MAGA\" credentials and a defiant stance against federal overreach to mobilize the party's grassroots. Early data suggests a May 26 runoff is almost certain, as neither Cornyn nor Paxton appears likely to clear the 50% threshold tonight. The result will determine whether Texas Republicans prefer a battle-tested legislator with massive fundraising power or a firebrand populist who promises a more confrontational approach in Washington.",
      status: "too-early",
      results: [
        { name: "John Cornyn", party: "R" },
        { name: "Ken Paxton", party: "R" },
        { name: "Wesley Hunt", party: "R" },
      ],
    },
    {
      id: "tx-senate-2026-d",
      title: "Texas U.S. Senate Democratic Primary",
      date: "2026-03-03",
      type: "primary",
      office: "congress",
      state: "Texas",
      stateCode: "TX",
      significance: "Marquee Democratic matchup: Crockett could appeal more to primary voters but would have a harder time winning a general election; Talarico is betting on broader appeal. The winner faces the GOP primary winner in a state that could become more competitive if Republicans nominate Paxton. The race also serves as a test of whether AIPAC-backed candidates are hurt by that sponsorship with Crockett being backed by AIPAC.",
      status: "too-early",
      results: [
        { name: "Jasmine Crockett", party: "D" },
        { name: "James Talarico", party: "D" },
      ],
    },
    {
      id: "me-senate-2026",
      title: "Maine U.S. Senate Democratic Primary",
      date: "2026-06-09",
      type: "primary",
      office: "congress",
      state: "Maine",
      stateCode: "ME",
      significance: "Nominee to challenge long-time incumbent United States Senator Susan Collins. Governor Janet Mills (Establishment) vs Graham Platner (Populist/Veteran). Platner has out-raised Mills with nearly $8 million in small-dollar donations, signaling a grassroots shift in a state that usually favors moderate Democrats.",
      status: "too-early",
      results: [
        { name: "Janet Mills", party: "D" },
        { name: "Graham Platner", party: "D" },
      ],
    },
    {
      id: "mi-senate-2026-d",
      title: "Michigan U.S. Senate Democratic Primary",
      date: "2026-08-04",
      type: "primary",
      office: "congress",
      state: "Michigan",
      stateCode: "MI",
      significance: "Open seat (United States Senator Gary Peters retiring). Three-way contest: United States Representative Haley Stevens (suburban moderate) vs State Senator Mallory McMorrow vs physician Abdul El-Sayed.",
      status: "too-early",
      results: [
        { name: "Haley Stevens", party: "D" },
        { name: "Mallory McMorrow", party: "D" },
        { name: "Abdul El-Sayed", party: "D" },
      ],
    },
    {
      id: "ak-senate-2026",
      title: "Alaska U.S. Senate Primary",
      date: "2026-08-18",
      type: "primary",
      office: "congress",
      state: "Alaska",
      stateCode: "AK",
      significance: "Incumbent Dan Sullivan (R) vs. former U.S. Representative Mary Peltola (D) vs. other major candidates. Peltola, the first Alaska Native in Congress, entered the race in January 2026. She is the only Democrat to win a statewide election in Alaska since 2008. Senator Lisa Murkowski (R), who previously endorsed Peltola for the House, has endorsed Sullivan in this race.",
      status: "too-early",
      results: [
        { name: "Dan Sullivan", party: "R" },
        { name: "Mary Peltola", party: "D" },
        { name: "Kelly Tshibaka", party: "R" },
      ],
    },
    {
      id: "fl-gov-2026",
      title: "Florida Governor Republican Primary",
      date: "2026-08-18",
      type: "primary",
      office: "governor",
      state: "Florida",
      stateCode: "FL",
      significance: "Governor Ron DeSantis is term-limited, so the race is a battle to see who inherits his \"Florida Blueprint.\" United States Representative Byron Donalds is the frontrunner with President Trump's endorsement, leading early polls at 37%–45% of the GOP vote. Challengers include Jay Collins (Lieutenant Governor) and Paul Renner (former Speaker of the Florida House). Matt Gaetz declined a run, which further solidified Donalds' lead.",
      status: "too-early",
      results: [
        { name: "Byron Donalds", party: "R" },
        { name: "Jay Collins", party: "R" },
        { name: "Paul Renner", party: "R" },
      ],
    },
    {
      id: "ca-gov-2026",
      title: "California Governor Primary",
      date: "2026-06-02",
      type: "primary",
      office: "governor",
      state: "California",
      stateCode: "CA",
      significance: "Governor Gavin Newsom is term-limited and will be leaving office. California uses a nonpartisan \"top-two\" primary: all candidates on one ballot; top two advance. Over a dozen major names. Republican Steve Hilton (former Fox News host) leads polls at 17%. Democrats are split: United States Representative Eric Swalwell (14%), United States Representative Katie Porter (10%), and Tom Steyer (9%).",
      status: "too-early",
      results: [
        { name: "Steve Hilton", party: "R" },
        { name: "Eric Swalwell", party: "D" },
        { name: "Katie Porter", party: "D" },
        { name: "Tom Steyer", party: "D" },
      ],
    },
    {
      id: "ga-gov-2026",
      title: "Georgia Governor Republican Primary",
      date: "2026-05-19",
      type: "primary",
      office: "governor",
      state: "Georgia",
      stateCode: "GA",
      significance: "Governor Brian Kemp is term-limited, leaving a vacuum in one of the nation's most important swing states. Lieutenant Governor Burt Jones has strong MAGA ties; Secretary of State Brad Raffensperger is known for high-profile disagreements with the Trump administration.",
      status: "too-early",
      results: [
        { name: "Burt Jones", party: "R" },
        { name: "Brad Raffensperger", party: "R" },
      ],
    },
    {
      id: "oh-gov-2026",
      title: "Ohio Governor Republican Primary",
      date: "2026-05-05",
      type: "primary",
      office: "governor",
      state: "Ohio",
      stateCode: "OH",
      significance: "Governor Mike DeWine is finishing his final term. Vivek Ramaswamy is the heavy favorite with endorsements from both President Trump and the Ohio Republican Party. He faces Heather Hill and Casey Putsch; with Trump's backing, Ramaswamy is expected to cruise through, potentially setting up a general election against Democrat Amy Acton (former state Health Director).",
      status: "too-early",
      results: [
        { name: "Vivek Ramaswamy", party: "R" },
        { name: "Heather Hill", party: "R" },
        { name: "Casey Putsch", party: "R" },
      ],
    },
  ],
};
